[build]
  command = ""
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# フォーム通知設定
[forms]
  [forms.contact]
    name = "contact"
    [forms.contact.fields]
      [forms.contact.fields.name]
        required = true
      [forms.contact.fields.email]
        required = true
      [forms.contact.fields.message]
        required = true

# Handle thank-you page
[[redirects]]
  from = "/thank-you"
  to = "/thank-you.html"
  status = 200

# Handle SPA routing (except for /admin and /thank-you)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Path = ["!/admin/*", "!/thank-you"]}

# Serve the admin page
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Ensure admin files are served with correct content-type
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-From = "netlify-headers"
    Cache-Control = "no-cache"
